# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d510f7f8a4fc0af422787be270b649db8a4d2982ef38de9c5fe5b6037c85db5d3cae9f9cb10364e8a9a30af5187c68dbb1f9484dc3d4ff6a10981abd4401bac6

test:
  secret_key_base: b6251d2697b0efeeae6fd3e67d68d6faf89fdeb8339e3791dcba674fbbeb0dcf3a0240c06173edaaebee9ad75d514174b43cf90b75d17a43d29cd232b562995f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

#test
